blueprint:
  name: IKEA SOMRIG (E2213) - Simple via Z2M (uden initial_press)
  description: >
    Simpel blueprint til IKEA SOMRIG shortcut button (E2213) via Zigbee2MQTT.
    Understøtter knap 1 og 2: klik, dobbeltklik, hold og slip.
    initial_press er fjernet for at undgå dobbelte triggere.
  domain: automation
  source_url: https://github.com/math7935/Home-Assistant-Blueprints/blueprints/automation/ikea_somrig_e2213_zigbee2mqtt.yaml
  input:
    remote:
      name: IKEA E2213 (Z2M device)
      selector:
        device:
          integration: mqtt
          manufacturer: IKEA
          model: "E2213"

    # -------------------------
    # KNAP 1
    # -------------------------
    button_1_click:
      name: "Knap 1 – Klik"
      default: []
      selector: { action: {} }

    button_1_double:
      name: "Knap 1 – Dobbeltklik"
      default: []
      selector: { action: {} }

    button_1_hold:
      name: "Knap 1 – Hold"
      default: []
      selector: { action: {} }

    button_1_release:
      name: "Knap 1 – Slip"
      default: []
      selector: { action: {} }

    # -------------------------
    # KNAP 2
    # -------------------------
    button_2_click:
      name: "Knap 2 – Klik"
      default: []
      selector: { action: {} }

    button_2_double:
      name: "Knap 2 – Dobbeltklik"
      default: []
      selector: { action: {} }

    button_2_hold:
      name: "Knap 2 – Hold"
      default: []
      selector: { action: {} }

    button_2_release:
      name: "Knap 2 – Slip"
      default: []
      selector: { action: {} }

mode: single
max_exceeded: silent

trigger:
  # --- KNAP 1 ---
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: 1_short_release
    id: b1_click

  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: 1_double_press
    id: b1_double

  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: 1_long_press
    id: b1_hold

  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: 1_long_release
    id: b1_release

  # --- KNAP 2 ---
  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: 2_short_release
    id: b2_click

  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: 2_double_press
    id: b2_double

  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: 2_long_press
    id: b2_hold

  - platform: device
    domain: mqtt
    device_id: !input remote
    type: action
    subtype: 2_long_release
    id: b2_release

action:
  - choose:
      - conditions: "{{ trigger.id == 'b1_click' }}"
        sequence: !input button_1_click
      - conditions: "{{ trigger.id == 'b1_double' }}"
        sequence: !input button_1_double
      - conditions: "{{ trigger.id == 'b1_hold' }}"
        sequence: !input button_1_hold
      - conditions: "{{ trigger.id == 'b1_release' }}"
        sequence: !input button_1_release

      - conditions: "{{ trigger.id == 'b2_click' }}"
        sequence: !input button_2_click
      - conditions: "{{ trigger.id == 'b2_double' }}"
        sequence: !input button_2_double
      - conditions: "{{ trigger.id == 'b2_hold' }}"
        sequence: !input button_2_hold
      - conditions: "{{ trigger.id == 'b2_release' }}"
        sequence: !input button_2_release
